name: Dependabot
on:
  schedule:
    - cron: '0 16 * * 1' # Run every Monday at 9 a.m. pacific time
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: dependabot/dependabot-core@v0.165.14
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: "/"
          update: true
